#:schema https://raw.githubusercontent.com/cloudflare/wrangler/main/packages/wrangler/config-schema.json
compatibility_flags = [ "nodejs_compat_populate_process_env" ]
compatibility_date = "2024-09-23"

[site]
bucket = ".vercel/output/static"
